### ISSUE TITLE
hello i need help with js and eris 

### ISSUE THREAD

**Issue by eissternchen-Leni** [eissternchen-Leni/mew#2]
hi i'm Learning the language than I need help

**Comment by ohlookitsAugust** [comment]
what d0 u need help with >~<

**Comment by eissternchen-Leni** [comment]
all i Need a host

**Comment by missingbinaries** [comment]
me

**Comment by missingbinaries** [comment]
or derpy

**Comment by eissternchen-Leni** [comment]
lol

**Comment by LevitatingBusinessMan** [comment]
This is discord.js not Eris lmao.
Also fork the repo next time

**Comment by missingbinaries** [comment]
I think he's well aware of that as it's his bot. He wants to transition to Eris but needs help starting out. Consider that before you post. ;)

**Comment by ohlookitsAugust** [comment]
yes

**Comment by LevitatingBusinessMan** [comment]
@missingbinaries No this is actually a broken version of https://github.com/LevitatingBusinessMan/Subaru. But I already helped eissternchen-Leni/Maxi with making his own.

**Comment by eissternchen-Leni** [comment]
thanks for help
